app:  # Используем префикс 'app' вместо 'storage' для согласованности
  storage:
    location: uploads  # Или абсолютный путь, например: "C:/uploads"
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    cors:
      allowed-origins: "http://localhost:5173"  # URL фронтенда (Vite/React)
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    path: /api/v1
logging:
  file:
    path: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  level:
    root: INFO
    com.study.geekshop: DEBUG
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss} %-5level %logger - %msg%n"
